### PR TITLE
Merge + Help Popups in {Commit, Log, Reflog} Views

### PR DESCRIPTION
**Pull request by gollth**
Found another couple of missing keybinds =)

### CODE REVIEW

**Comment by CKolkey** [comment]
Merge popup is an easy ✅ 

Help popup I think is a little weird. It's pretty tightly coupled to the status buffer (the stage/unstage commands are all baked in) and it doesn't have the ability to get the current commit under the cursor so will behave differently when opening a popup from the help menu vs directly.

My plan for that is to do some/all of the following:
- Make the help popup more composable so callers can modify what gets shown
- Pass `commits` into help popup constructor so they can be passed into any popups that are opened up from the help menu
- Create different help popups for each view

**Comment by gollth** [comment]
Ah okay, didn't look that closely to the help popup (was just wondering why trying to open it brought up a vim search :D)

I will revert the keybind commit for now, than until the preps for the customizable help are ready. All points sound very resonable to me

**Comment by CKolkey** [comment]
Cool! Thanks as always :)

**Comment by gollth** [comment]
Thank you for this plugin =)

**Pull request merged**
