### PR TITLE
[Neovim Nightly] 0.10

### LINKED ISSUE #1250: Making a new branch should refresh the status buffer
### Description

This is similar to #1240. After creating a new branch, the status buffer doesn't update.

### Neovim version

NVIM v0.10.0-dev-2818+gae28ef327
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188

### Operating system and version

Linux 6.7.9-amd64

### Steps to reproduce

1. Go to any git directory
1. `nvim -nu minimal.lua`
1. `:Neogit`
1. Make a new branch with `b c` from any existing branch

### Expected behavior

The Ui should update to show the new branch details.

### Actual behavior

The previous state is still shown.

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

### PR DESCRIPTION
**Pull request by CKolkey**
Todo: Set up CI action to auto merge master into Nightly, presuming no conflicts.

Changes that will land in Master when Neovim 0.10 is released.
- Rewritten folding to use native folds instead of internal state.
- Added RefsView buffer. 
- Use new extmarks api for line highlighting/signs
- Use new options api
- Rewritten status buffer using UI framework
- Improved Rebase section for status buffer
- Added rebase_editor and commit_editor insert mode specific mappigns
- Added ability to remap `OpenOrScrollUp` and `OpenOrScrollDown`
- Removed remaining `ftpugin/*.vim` files
- Removed `require("neogit").refresh_viml_compat()`
- ? Removed `require("neogit").refresh_manually()`
- Completely rewritten status buffer
- Remove old bootstrap.lua file
- Added a header to the commit-select view, with instructions
- Added status column override
- Improved how "is the buffer open" is checked internally
- Better support for showing the correct SHA hash length in UI
- Fix height of fuzzy finder always being `0.3` instead of a computed value
- Use mapped key to close git command history
- Use native folds in git command history
- Added `NEOGIT_DEBUG` env var, which will show, among other things, git CLI calls that are otherwise hidden from the user.
- Use native folds for log view
- Added `OpenOrScrollDown` and `OpenOrScrollUp` to status buffer, reflog buffer, and refs buffer
- Extend the "Close" mapping to close the topmost "layer", even if unfocused.
- Adds a diff view to the commit editor, so you can see the changes you're about to commit.
- Adds `Untrack` (bound to `K`)

### Refs View:
- [ ] Finalize Keybindings
### Docs:
- [ ] Bisect Popup Documentation

### Status:
- [ ] Status buffer loses context highlighting when telescope picker is activated (`b l`). Commit view doesn't.
- [ ] Status buffer might not render a diff with highlights when a notification (popup window) is present. Probably related to above.

Closes #1250, #1240, #1160, #1192, #1170, #1171, #1156, #1155, #1140, #1130, #1109, #1096, #955, #951, #909, #515, #714, #509, #122, #334, #58, #335, #1248, #1291

### CODE REVIEW

**Comment by CKolkey** [comment]
Yeah, there are some API's that dont exist on 0.9 that I'm using. The only one so far is for fold-text to use the extmarks api for nice highlighting, but there are (loose) plans to use the new `vim.system` api to replace the async jobs. I'm not going to go out of my way to break stuff, but... i expect it to happen.

What I can do is tag the commit before I merge this for 0.9 compatibility, so people can pin to that if they need.

**Comment by CKolkey** [comment]
Thanks @ofseed - fixed

**Comment by ofseed** [comment]
Thank you for your fix. I found that after the fix, diffview works well but the diff buffers have a `'statuscolumn'` set by neogit. Maybe it is not needed?

**Comment by CKolkey** [comment]
> Is this expected to break on older versions of neovim when merged?

You can pin to: https://github.com/NeogitOrg/neogit/releases/tag/v0.0.1

**Pull request merged**
