### PR TITLE
format drive letter for per_project_settings

### PR DESCRIPTION
**Pull request by setibeings**
Absolute paths in windows always start with a drive letter which has to be stripped or formatted. As far as I can tell from my testing this makes detecting the platform unnecessary, as the base path and filename don't need further modification, and stripping a drive letter that isn't there is harmless.

This resolves issue https://github.com/NeogitOrg/neogit/issues/469

### CODE REVIEW

**Comment by setibeings** [comment]
I want to take a crack at writing or rewriting some tests around this, so if you were to hold off til I get time to take another look (a day or two, I hope) I can better demonstrate that this code works. I probably should have done it before opening the PR, but I would still like to do it now.

**Comment by CKolkey** [comment]
Sure, fine with me :)

**Comment by wrightjjw** [comment]
Is plenary path normalize not sufficient in this case?

**Comment by setibeings** [comment]
well, the branch name isn't really accurate anymore, I realized that simply discarding drive letters would be bad say if somebody has a project with the same folder name on the roots of different drives. I never wrote automated tests, but in my manual testing the files get equivalent names to what they got before on linux. I didn't test it on windows with `:set shellslash` because that setting works poorly with other packages I have installed, but I don't know of a reason that this change in particular would break that option in neovim.

**Comment by setibeings** [comment]
Although I wanted to write unit tests, this could probably be merged as is, if there isn't a hard requirement to unit test all code changes. An end to end manual test of this fix is just to check that the state file is created with the expected name, in the expected place, and of course that Neovim doesn't crash on startup when `vim.loop.os_uname().sysname` returns something other than"Windows_NT" on windows.

**Comment by setibeings** [comment]
I applied the changes from stylua

**Comment by CKolkey** [comment]
Looks good to me! Thanks for the fix.

**Pull request merged**
