### PR TITLE
feat: add annotations for the Neogit config

### PR DESCRIPTION
**Pull request by treatybreaker**
Follow up for #631 

This adds annotations for the Neogit config and applies them for the `setup` function.

This makes it *much* easier to configure Neogit within Neovim for users of the [Lua Language Server](https://github.com/LuaLS/lua-language-server)

See below for a quick demo:

https://github.com/NeogitOrg/neogit/assets/58627896/4cd9a0f4-b53e-4701-8ee8-c16326bd73c8

### CODE REVIEW

**Comment by CKolkey** [comment]
Hot damn 🤩  Request a review when this is done ;)

**Comment by treatybreaker** [comment]
> Hot damn 🤩 Request a review when this is done ;)

Since the last force push https://github.com/NeogitOrg/neogit/commit/710bde37961e16c7bc647f3624d356c3e85896b2 it should be good to go.

**Comment by treatybreaker** [comment]
Ok, now it is 100% ready to go. I can't find anything else. I was wrong previously, I'm nearly 100% confident now.

Annoying that for annotations you can't really do any sort of tests or type checking.

**Comment by treatybreaker** [comment]
> Hot damn 🤩 Request a review when this is done ;)

Also, I can't do this. I think only Collaborators or Members can directly request reviews, might be wrong though.

**Comment by CKolkey** [comment]
> > Hot damn 🤩 Request a review when this is done ;)
> 
> Also, I can't do this. I think only Collaborators or Members can directly request reviews, might be wrong though.

Oops! Thats right. Alright, ignoring that detail...

**Pull request merged**
