### PR TITLE
Always reset status when opening neogit

### PR DESCRIPTION
**Pull request by smatting**
Fixes https://github.com/NeogitOrg/neogit/issues/931

### CODE REVIEW

**Review by ten3roberts — APPROVED** [review]
Amazing, simple and easy solution.

The dreaded enemy of all programmers: *cache invalidation*

**Comment by ten3roberts** [comment]
As for the tests, it is likely they fail as they assume neogit opens and has the correct state immediately, but now such happens in the next event loop tick.

There may be an easy "wait for everything to open" for those tests

**Comment by smatting** [comment]
> The dreaded enemy of all programmers: cache invalidation

Maybe the cleanest way would be not to cache this at all. Any objections against trying this?

**Comment by CKolkey** [comment]
I'm up to try, sure :)

**Comment by smatting** [comment]
Closing this in favor of https://github.com/NeogitOrg/neogit/pull/944

**Pull request closed without merging**
