### PR TITLE
Fix/config validation

### PR DESCRIPTION
**Pull request by treatybreaker**
This PR ensures the config validation properly passes for mappings that use `false` to disable them. This PR also adds new tests for this and removes and updates invalid tests to be correct.

@CKolkey 

Resolves the new problem from #635

### CODE REVIEW

**Comment by CKolkey** [comment]
Thanks for the quick fix ;)

**Comment by treatybreaker** [comment]
@CKolkey 

Revert and let me reopen a new PR, I should have marked this as a draft. There's a minor issue I just discovered causing a full freeze of the Neovim client and somewhat incorrect config validation messages.

**Comment by CKolkey** [comment]
Ah, my bad. I saw the thumbs up as "good to go". But yeah, if you stick to draft/ready convention, thats super easy to follow :)

**Comment by treatybreaker** [comment]
> Ah, my bad. I saw the thumbs up as "good to go". But yeah, if you stick to draft/ready convention, thats super easy to follow :)

That's my fault, I *thought* it was good until I realized at the last moment that it, in fact, was not.

**Comment by CKolkey** [comment]
Haha, never been there, no sir, can't relate at all.... 🤣🤣

**Pull request merged**
