### PR TITLE
Add flag to include author information in recent commits

### LINKED ISSUE #652: Add Author Column to Recent Commits
**Is your feature request related to a problem? Please describe.**
I find myself frequently wanting to see the author when viewing `Recent commits`, but most of the times I'm too lazy to press enter on the commit to inspect it's details. 

**Describe the solution you'd like**
I would like the author of the commit to also be included in `Recent commits` as a separate column so I can quickly see who authored the commit.

**Describe alternatives you've considered**
Start exercising, change my diet, work on my relationships, all in a futile effort to overcome my laziness. 

**Additional context**
image

### PR DESCRIPTION
**Pull request by treatybreaker**
This PR does the following:
- Adds capability to show author name and email in recent commits
  - By default this is disabled, it can be enabled by setting `status.recent_commits_include_author_info` to `true`
- Adds syntax matching for recent commit messages to color this new information
- Adds tests to cover this new functionality and prior functionality that wasn't being tested
- Updates the Readme to reflect the new flag

See below for how the recent commits look with the author information included:
image

Closes #652 😌

### CODE REVIEW

**Comment by treatybreaker** [comment]
Ok, I'm losing sanity. This Works On My Machine™, but fails in the CI.

The recent commits section should have the number of recent commits in it, right?

Mine looks like so:
image

I'm assuming that in between those parentheses should be the number of recent commits as found by `status.recent_commit_count`. Should be embedded on this line over here: https://github.com/NeogitOrg/neogit/blob/3d63d76f04dc7102c83a057ded30a93822b59dec/lua/neogit/status.lua#L206

The only reason the "Recent commits" message would have more than 10 is if this line https://github.com/NeogitOrg/neogit/blob/3d63d76f04dc7102c83a057ded30a93822b59dec/lua/neogit/lib/git/log.lua#L268 `--max-count` flag is somehow receiving a different number than `config.values.status.recent_commit_count`.

I'm not sure how this is happening, but it's driving me up a wall. Any idea @CKolkey @ten3roberts?

**Comment by CKolkey** [comment]
What would be REALLY cool is to work towards how magit handles this:
Screenshot 2023-07-21 at 07 47 32

(If you don't have emacs installed, I recommend grabbing DOOM emacs to use as a reference.)

^^ Thats the Log Margin popup https://magit.vc/manual/magit/Log-Margin.html

Using "toggle details" can turn on showing the author name:
Screenshot 2023-07-21 at 07 50 26


I think it would be super cool to implement this as the config mechanism instead of have it be hard-coded config values. You can use the state module to write/read persistent values. And an easy way to do perfect right-aligned text is with virtual text - thats how I did in the reflog view.

It also seems like magit shows the recent commits across _all_ branches, which would be really cool to copy. Then we can show the remote/branch for the commit too.. That doesn't need to be part of this change, just had never noticed that before.

**Comment by CKolkey** [comment]
> Ok, I'm losing sanity. This Works On My Machine™, but fails in the CI.
> 
> The recent commits section should have the number of recent commits in it, right?
> 
> Mine looks like so: image
> 
> I'm assuming that in between those parentheses should be the number of recent commits as found by `status.recent_commit_count`. Should be embedded on this line over here:
> 
> https://github.com/NeogitOrg/neogit/blob/3d63d76f04dc7102c83a057ded30a93822b59dec/lua/neogit/status.lua#L206
> 
> The only reason the "Recent commits" message would have more than 10 is if this line
> 
> https://github.com/NeogitOrg/neogit/blob/3d63d76f04dc7102c83a057ded30a93822b59dec/lua/neogit/lib/git/log.lua#L268
> 
> `--max-count` flag is somehow receiving a different number than `config.values.status.recent_commit_count`.
> I'm not sure how this is happening, but it's driving me up a wall. Any idea @CKolkey @ten3roberts?

Hmm. That seems right to me. Whats the actual number being shown in CI?

**Comment by treatybreaker** [comment]
> > Ok, I'm losing sanity. This Works On My Machine™, but fails in the CI.
> > The recent commits section should have the number of recent commits in it, right?
> > Mine looks like so: image
> > I'm assuming that in between those parentheses should be the number of recent commits as found by `status.recent_commit_count`. Should be embedded on this line over here:
> > https://github.com/NeogitOrg/neogit/blob/3d63d76f04dc7102c83a057ded30a93822b59dec/lua/neogit/status.lua#L206
> > 
> > The only reason the "Recent commits" message would have more than 10 is if this line
> > https://github.com/NeogitOrg/neogit/blob/3d63d76f04dc7102c83a057ded30a93822b59dec/lua/neogit/lib/git/log.lua#L268
> > 
> > `--max-count` flag is somehow receiving a different number than `config.values.status.recent_commit_count`.
> > I'm not sure how this is happening, but it's driving me up a wall. Any idea @CKolkey @ten3roberts?
> 
> Hmm. That seems right to me. Whats the actual number being shown in CI?

CI is getting `51` back instead of `10` for that.

**Comment by treatybreaker** [comment]
> What would be REALLY cool is to work towards how magit handles this: Screenshot 2023-07-21 at 07 58 02
> 
> (If you don't have emacs installed, I recommend grabbing DOOM emacs to use as a reference.)
> 
> ^^ Thats the Log Margin popup https://magit.vc/manual/magit/Log-Margin.html
> 
> `L` opens this popup.
> 
> Using "toggle details" can turn on showing the author name: Screenshot 2023-07-21 at 07 50 26
> 
> I think it would be super cool to implement this as the config mechanism instead of have it be hard-coded config values. You can use the state module to write/read persistent values. And an easy way to do perfect right-aligned text is with virtual text - thats how I did in the reflog view.
> 
> It also seems like magit shows the recent commits across _all_ branches, which would be really cool to copy. Then we can show the remote/branch for the commit too.. That doesn't need to be part of this change, just had never noticed that before.

That's neat, I used emacs for a while, but stuck to CLI git. My exposure to Magit is entirely via Neogit.

I'll see what it'll take to replicate that.

**Comment by CKolkey** [comment]
> That's neat, I used emacs for a while, but stuck to CLI git. My exposure to Magit is entirely via Neogit.
> 
> I'll see what it'll take to replicate that.

Haha, no kidding. My only exposure to emacs is for referencing stuff to implement in Neogit.

It should be pretty simple to add the popup. You'll need:

`popups/log_margin/init.lua`
`popups/log_margin/actions.lua`

Just copy the pattern used by all the other popups. `actions` exports each function of the popup as a function. For testing, only the branch popup's actions are properly wrapped by the operations module. Thats a decent reference.

Otherwise, as you'll see, each action takes the `popup` as it's first/only argument, and the popup object has `popup:get_arguments()`
to see which config/options are enabled. Other than that, it should be pretty simple. @ten3roberts just updated the popups api so you should need to add fewer references to get this referenced in multiple places.

**Comment by treatybreaker** [comment]
Cool!

I guess I'll make this my next goal with Neogit -- nice stuff for the recent commits buffer.

This is gonna take a minute... well into the breach I go.

**Comment by treatybreaker** [comment]
Closing this in favor of a full fledged popup PR.

**Comment by CKolkey** [comment]
It's a breaking change, but changing the log popup to `l` and taking `L` for this is fine. I'd like to align with magit as much as is reasonable.

**Pull request closed without merging**
