### PR TITLE
Add cherry-pick options/switches

### PR DESCRIPTION
**Pull request by ej-shafran**
Not sure why these options were in a `TODO` comment; do we maybe need to keep it as a comment?

### CODE REVIEW

**Comment by CKolkey** [comment]
I think I marked those as a TODO quite a while ago and never revisited them. Have you tested that they all work as expected?

**Comment by ej-shafran** [comment]
So far I've only tested `mainline`, which seems to work just fine. I'll check the others.

Could it be that these were marked as TODO because `switch_if` and `option_if` did not exist? They _were_ written as `switch` and `option` in the original comment...

**Comment by CKolkey** [comment]
Yeah, could have been. I also didn't understand a lot of the internals of this app yet, especially how all the async stuff worked. I'll go over what you've got and see what needs fixing up :)

**Comment by CKolkey** [comment]
Really appreciate you picking this up! It's easy to forget to uh.. do.. the todos 😅

**Pull request merged**
