### PR TITLE
Provide full installation example for Lazy distro

### PR DESCRIPTION
**Pull request by Gleland**
Hello! Thanks for making this awesome plugin. I added a short change to make the `Lazy` install a bit more copy-paste. Thanks for your time!

### CODE REVIEW

**Comment by CKolkey** [comment]
I think you can also just pass `opts = {}` instead of a function to config.

**Comment by vheon** [comment]
> I think you can also just pass `opts = {}` instead of a function to config.

when you just want to run the setup one can simply `config = true`

**Comment by Gleland** [comment]
>when you just want to run the setup one can simply config = true

even better! Thanks for the feedback, I've just updated it.

**Review by ten3roberts — APPROVED** [review]

**Comment by ten3roberts** [comment]
Thanks, looks great. Always good to mention the plugin manager that a lot of people, including me use

**Pull request merged**
