### PR TITLE
fix: make neogit respect user's configuration of diffview

### PR DESCRIPTION
**Pull request by milkias17**
mentioned in #550

### CODE REVIEW

**Comment by milkias17** [comment]
@ten3roberts Any problems with the implementation😅?

**Review by ten3roberts — COMMENTED** [review]
I suppose this works by not replacing the table reference, but rather works and mutates the existing reference?

**Comment by milkias17** [comment]
Yup exactly. We are basically using the exact same method that [diffview.nvim](https://github.com/sindrets/diffview.nvim/blob/b0cc22f5708f6b2b4f873b44fbc5eb93020f4e0c/lua/diffview/config.lua#L628) uses to merge the default configuration with the users configuration.

**Review by ten3roberts — APPROVED** [review]

**Comment by ten3roberts** [comment]
Is this all done or is there anything more you want to get in?

Thanks for your help, I'm looking forward to having *neogit invoked* diffview be consistent with the *user invoked* diffview 🚀

**Comment by milkias17** [comment]
Yea interms of repsecting user's configuration that's about it. However the thing mentioned about having a keybinding to invoke the commit popup within the diffview buffer, should I add that or?

**Comment by ten3roberts** [comment]
Perhaps that feature would be best under a config option, since some people may not want their difftview keybindings to be different and inconsistent. There is an in-progress PR which modifies the config file, so if we do this it would be best as another PR after that one.

**Pull request merged**
