### PR TITLE
fix: escape $ in filepath

### PR DESCRIPTION
**Pull request by andrewcohen**
Fixes `GoToFile` in the status view for file paths containing `$` i.e `products.$id.tsx`

### CODE REVIEW

**Comment by CKolkey** [comment]
Would `vim.fn.fnameescape()` work for this? (https://neovim.io/doc/user/builtin.html#fnameescape())

**Comment by CKolkey** [comment]
Update: Would you let me know if https://github.com/NeogitOrg/neogit/pull/966 fixes your issue?

**Comment by CKolkey** [comment]
Closing in favor of https://github.com/NeogitOrg/neogit/pull/966

**Comment by andrewcohen** [comment]
I am on macos and the fix in #966 works for me! Thanks!

**Pull request closed without merging**
