### PR TITLE
Bugfix: remove duplicate tag

### LINKED ISSUE #565: Installation error: Duplicate tag
### Description

Unable to install using lazy.nvim. Got the error below.

```
  Failed (1)
   * neogit 
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:79: Vim:E154: Duplicate tag "neogit_c" in file /Users/ctran/.local/share/nvim/lazy/neogit/doc//neogit.txt
```

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS Ventura 13.4

### Steps to reproduce

Add block below to lazy.nvim plug list.

```
return {
  "NeogitOrg/neogit",
  dependencies = "nvim-lua/plenary.nvim",
}
```

### Expected behavior

Plugin should be installed.

### Actual behavior

Plugin didn't install and errored out.

### Minimal config

```Lua
return {
  "NeogitOrg/neogit",
  dependencies = "nvim-lua/plenary.nvim",
}
```
```

### PR DESCRIPTION
**Pull request by CKolkey**
Fixes #565

### CODE REVIEW

**Comment by bmulholland** [comment]
Confirm this fixed it, though I had to manually check out the commit, as lazy.nvim couldn't seem to get over the error on its own

**Comment by CKolkey** [comment]
Lame. Thanks for letting me know :)

**Comment by ckt114** [comment]
It's still failing even though I've added `commit = "e00d635eaa750bd31264b74cbb03c703e1450002"` to lazy.

**Comment by CKolkey** [comment]
Can you try removing it entirely, close nvim, repoen, make sure lazy can remove it, then re-add it without the commit?

**Comment by ckt114** [comment]
Yes, I did all that. Steps I did.
1. Remove `neogit.lua` from `plugins` folder
2. Restarted nvim and go in lazy UI and did `X`
3. Exit nvim
4. Copied `neogit.lua` back into `plugins` folder
5. Started nvim and the installation start and it throws the error

**Comment by CKolkey** [comment]
Thanks - it was in two places: https://github.com/NeogitOrg/neogit/pull/569

**Comment by ckt114** [comment]
Works now. Thanks.

**Pull request merged**
