### PR TITLE
Log popup issues

### PR DESCRIPTION
**Pull request by levouh**
See #258 for some details on the issue. Not really sure what the solution is, but this seems like it might be a way to do it. Looking for feedback on what the right way is so I can make the changes. Having a proper log viewer would be awesome.

### CODE REVIEW

**Comment by levouh** [comment]
@TimUntersberger would love some feedback if you have the time.

**Comment by TimUntersberger** [comment]
Hey @levouh,

I just read your comments on the issue and I'm not sure what the purpose of the `_switch` is. Your initial solution is the correct way to handle this imo. 

As @chuck-flowers pointed out, neogit always should be parsing the log as a graph, since it contains a lot of additional information. The graph switch is intended for changing the visual representation.

Also thank you for opening a PR.

**Comment by levouh** [comment]
Yes, so as I interpreted it there are two kinds of "flags" here. Those for `neogit`, and those for `git`.

Some have options, like `--max-files=...` and some are just "togglea" (or switches).

Rather than copy `"--graph"` to every line in this portion of the code (something others then have to remember to do if more things are added), `_switch` serves as an "internal switch" to the `git` flags that `neogit` uses (could be named better for sure).

The part that I wasn't sure about is that seem more like they are for the `popup` than the actual "command generator", however this _seemed_ like the only place to add flag handling like this.

**Comment by TimUntersberger** [comment]
I'd suggest to just extract ```git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments()))``` into a function.

This is such a simple problem that I don't think adding some complex solution is worth it.

**Pull request closed without merging**
