### PR TITLE
When a user is running nvim 0.10, show a message about the 'nightly' branch

### PR DESCRIPTION
**Pull request by CKolkey**

### CODE REVIEW

**Comment by avegancafe** [comment]
Is there a migration guide anywhere by any chance for upgrading to nightly? Like for neogit specifically. I set `branch = nightly` in my lazy.nvim config, but now I can't commit anything

**Comment by CKolkey** [comment]
That doesn't sound right.. i've been using nightly for months now. Do you mind opening a bug report? It should be as easy as "set and forget"

**Comment by avegancafe** [comment]
Haha that's what I thought too, yeah I'll try to do that later today!

**Comment by avegancafe** [comment]
Submitted here: https://github.com/NeogitOrg/neogit/issues/1236 @CKolkey

**Pull request merged**
