### PR TITLE
fix: replace os.execute with vim.system to prevent stdout from messin…

### LINKED ISSUE #801: Unintentional printing when lazy loaded
### Description

When neogit is lazy loaded `os.execute` commands display their output.

Issue line: https://github.com/NeogitOrg/neogit/blob/797e3a7b1041b4b3e281f62ba3d0aca289825aaa/lua/neogit/config.lua#L141

### Neovim version

```
NVIM v0.10.0-dev-985+gae7ab90159
Build type: RelWithDebInfo
LuaJIT 2.1.1692616192
Run "nvim -V1 -v" for more info
```

### Operating system and version

Arch

### Steps to reproduce

1. `nvim -vu minimal_lazy.lua`
2. `:Neogit`

### Expected behavior

_No response_

### Actual behavior

image

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
	cmd = "Neogit",
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

### PR DESCRIPTION
**Pull request by cristiansofronie**
…g up the screen

Stdout from os.execute messes up the screen. This uses vim.system to fix it. This closes #801 .

### CODE REVIEW

**Comment by CKolkey** [comment]
Only issue is that `vim.system` is on nightly, not stable. Can you do a check first, or use the older api?

**Comment by cristiansofronie** [comment]
We could use vim.fn.system and get the return code from v:shell_error. From the docs:
		Gets the output of {cmd} as a |string| (|systemlist()| returns
		a |List|) and sets |v:shell_error| to the error code.

**Comment by CKolkey** [comment]
Fine with me.

**Comment by cristiansofronie** [comment]
Or even better there is:

vim.fn.executable({expr})

**Comment by CKolkey** [comment]
There it is! I swear I knew this existed, just... couldn't think of the name. Thanks.

**Pull request merged**
