### PR TITLE
Release Candidate

### PR DESCRIPTION
**Pull request by CKolkey**
Alright, here's the release candidate branch. It includes everything we've reviewed so far, and all the changes made, while keeping a linear git history.

I backported a few bug fixes here: https://github.com/NeogitOrg/neogit/pull/554/commits/ee502d84ff2967ec2c3cea6a1c28b74897b34dcc 
https://github.com/NeogitOrg/neogit/pull/554/commits/66bdfe592b038fbeb129921a05e2d45b1ebd097a
https://github.com/NeogitOrg/neogit/pull/554/commits/ae3dbe54723b3e214d2c0b8dc432a74d21deb69f

Additionally, added:
- Ability to set the desired telescope sorter if the default isn't what the user likes
- Rewrote config values to be OO in style - they've been a constant source of headache checking for "unset", so hopefully this alleviates that
- Fixed a bug where CLI options with values would have the value set to `unset` when blanked.. which isn't right. Should be blank.
- Added `config.fn` for config actions that are a function, and moved `config.callback` to be at the end, like a callback.
- Log view - `log_other` action.

### CODE REVIEW

**Comment by wrightjjw** [comment]
I'll take a look at this sometime this week! Got sick over the weekend, but if I'm feeling well enough I'll play with it at home tomorrow.

**Comment by ten3roberts** [comment]
I am finding that `ri` with the cursor on a commit will not search for and jump to that commit.

Furthermore, it appears that the commit select view of rebase interactive is a full screen graph. Not sure if intended behavior.

Screenshot 2023-07-11 at 16 10 55

**Comment by CKolkey** [comment]
I added some stuff that simplifies how finding/setting a pushremote works, and tweaks the logic for rebasing onto the branch's pushremote. Added a `b` action to the rebase popup to rebase onto `base`, which would normally be either `master` or `main` for most projects.

Sorry for making this a moving target - hopefully the change makes sense.

**Comment by ten3roberts** [comment]
> I added some stuff that simplifies how finding/setting a pushremote works, and tweaks the logic for rebasing onto the branch's pushremote. Added a `b` action to the rebase popup to rebase onto `base`, which would normally be either `master` or `main` for most projects.
> 
> Sorry for making this a moving target - hopefully the change makes sense.

Yeah I did notice that. Must be the first time I pushed to the correct repo when creating a new branch 😄 . Getting the prompt for `origin, fork upstream, etc` was a pleasant surprise rather than `push to pushremote` and crossing your fingers you don't end up creating a branch on a fork.

Don't worry about that it is withing manageable levels. I understand the temptation to add new small things.

Do you know why it can't be rebased?

I'll diff this branch against the previous `tmp-master` and `ckolkey` merge to see if there is any diffs

**Comment by ten3roberts** [comment]
Do you think we could forgo modifying the tests at the moment and get this merged instead, and then add the tests afterwards?

**Comment by ten3roberts** [comment]
> Good call. What I did to check that is duplicate the repo directory, and check out this branch in one, and `tmp-master` in the other. then run `diff -uraN ./lua ../neogit-other/lua` from the source of truth - that matters if the diff will be an addition or deletion. You can redirect that via `> patch.diff` to make a diff, and `patch --dry-run -p1 -i patch.diff` to apply it (remove the dry-run flag to do it for real). Maybe you knew that already, but I just learned about those :)
> 
> Mind you, you _will_ see differences, since this branch contains things that those don't. But, importantly, those branches _don't_ contain anything that this doesn't. I used the above `diff`/`patch` process to go through all the differences one-by-one. I found that easier than using git, since git produces conflicts, and I really just wanted deltas.

I also had that idea, but then I thought to myself: *wait a minute, my neovim "editor" is bolstered to the bring for every use case, it should handle this instead.*

```ex
:DiffViewOpen merged-master-tmp
```

Et voilà:

Screenshot from 2023-07-12 23-11-13


:sweat_smile: 

It is not a spaceship, but a space station at this point.

In any case I will look through the diff and see if there is anything eye catching

**Review by ten3roberts — COMMENTED** [review]
The differences between this and #544 are minimal and mostly naming semantics.

The only remaining thing to fix is the rebase *commit under cursor* and the recent test spec failures, and then feel free to press merge.

I really like how well the FuzzyFinder fits in like a puzzle piece in all the functions whenever there are multiple answers, like pushing a new branch :+1:

**Comment by CKolkey** [comment]
> Do you think we could forgo modifying the tests at the moment and get this merged instead, and then add the tests afterwards?

Yeahhhhh 😅 


```
:DiffViewOpen merged-master-tmp
```

... Yea, what was I thinking. Thanks XD

> The only remaining thing to fix is the rebase commit under cursor and the recent test spec failures, and then feel free to press merge.

Oh, I fixed the rebase-commit-under-cursor here: [`9762eef` (#554)](https://github.com/NeogitOrg/neogit/pull/554/commits/9762eef6a10cccbe6641a004793f9ae0d96ac2f6). Thats what you meant, right?

> I really like how well the FuzzyFinder fits in like a puzzle piece in all the functions whenever there are multiple answers, like pushing a new branch 👍

100% agreed - the fuzzy finder buffer has been an absolutely invaluable tool in expanding what this plugin can do.

**Review by ten3roberts — APPROVED** [review]
Thanks for your amazing work.

It is ready to merge using whichever method you prefer, I'll leave you the honors of pressing the shiny green button, which will cause a freight train of 509 commits and +6072 changes to come hurtling into master at mach speed.

**Comment by CKolkey** [comment]
> Thanks for your amazing work.
> 
> It is ready to merge using whichever method you prefer, I'll leave you the honors of pressing the shiny green button, which will cause a freight train of 509 commits and +6072 changes to come hurtling into master at mach speed.

Hahaha, hell yeah. And this is just a start :P

**Comment by ten3roberts** [comment]
How are you planning now going forwards?

Will you keep working on your fork or move your work here all together?

**Comment by CKolkey** [comment]
Probably just move to branches on this repo, to take advantage of the CI setup. Since I can merge stuff more often, there's no issue of 'the branch I'm working on needs commits from that other branch'

**Comment by gegoune** [comment]
Feel free to hide this pass by comment (or should I open an issue for that?).

Well done on all your hard work!

I am getting an error when running setup (at nvim's startup) when not in git repo:
```
git rev-parse --show-toplevel:
fatal: not a git repository (or any of the parent directories): .git
Open the console for details
```

**Comment by ten3roberts** [comment]
Time to first bug: 52 minutes 🤭

**Pull request merged**
