### PR TITLE
chore: remove doc/tags

### PR DESCRIPTION
**Pull request by ten3roberts**
This fixes the error when updating Neogit through an auto-indexing plugin manager such as lazy. See https://github.com/NeogitOrg/neogit/discussions/628#discussioncomment-6492754

For the users they may need to once more do the `git restore doc/tags` dance as `docs/tags` would be in the state of `modified by us, deleted by them` or `UD`

### CODE REVIEW

**Comment by ten3roberts** [comment]
```vim
:Lazy sync
```

image

Caused by going from `master` to the `remove-tags` branch in plugin spec and updating (after removing local dev overrides)

**Comment by ten3roberts** [comment]
This will be a breaking change, so I added the requested tracking issue for those

**Comment by ten3roberts** [comment]
@CKolkey what do you think about this breaking change?

`auto-session` had to do a similar breaking change a few months ago

**Comment by CKolkey** [comment]
I'm totally fine with this, but I'm not sure how this is a breaking change. What will users need to do?

**Review by CKolkey — APPROVED** [review]

**Comment by ten3roberts** [comment]
The breaking commit is that users may need to go and explicitely restore the repo inside `~/.local/share/nvim/lazy/neogit` as lazy will fail to pull as `tags` may be changed locally due to the aforementioned auto-indexing

**Pull request merged**
